### ISSUE TITLE
[ENH] Specify ID of the first post of a discussion

### ISSUE THREAD

**Issue by Leogomat** [rwth-acis/moodle-data-proxy#32]
1. **Motivation** - In its current state, the data proxy does not include the post ID of the first post of a discussion in the xAPI statements generated when a new discussion is created.
2. **Specification** - The ID of the first post of a discussion needs to be made available in the generated statements (for example, by appending it to the discussion ID or by generating a statement of the form "user posted post" for the first post of a discussion).
3. **Finalised state** - The post ID of the first post of a discussion is specified in the xAPI statements generated when a new discussion is created.

**Comment by BorisJov** [comment]
Added post ID as context extension
